name: CI


on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure JDK 17
          uses: actions/setup-java@v4
          with:
            distribuition: temurin
            java-version: 17
            cache: maven

        - name: Build (Without Tests)
          run: mvn -B -DskipTests package

        - name: Tests
          run: mvn -B test